export const data = [
  {
    id: "1",
    name: "Poha",
    price: 20,
    type: "Snacks",
    meal: "Breakfast",
    avlaibility: "Yes",
    marathi_name: "पोहा ",
    description:
      "Pohe is flattened rice that is steam cooked with onions, spices and herbs.",
  },
  {
    id: "2",
    name: "Upma",
    price: 20,
    type: "Snacks",
    meal: "Breakfast",
    avlaibility: "Yes",
    marathi_name: "उपमा",
    description: "Upma is a flat rice cake made from fermented rice.",
    // description: "Upma is a flavorful South Indian breakfast dish made from rava in water that has been flavored by ghee (or oil), cashews, urad dal (lentils), chana dal (husked chickpeas), onion, ginger and additional herbs and spices. Sugar can be added for a mildly sweet and savory dish.",
  },
  {
    id: "3",
    name: "Poha Upma mix",
    price: 20,
    type: "Snacks",
    meal: "Breakfast",
    avlaibility: "Yes",
    marathi_name: "पोहा  उपमा मिक्स",
    // description: "This dish is usually mixtrue of poha and upma in this you will get half of plate poha and upma in this",
    description: "This dish is usually a mixtrue of poha and upma",
  },
  {
    id: "4",
    name: "Shira",
    price: 20,
    type: "Snacks",
    meal: "Breakfast",
    avlaibility: "Yes",
    marathi_name: "शिरा",
    // description: "A simple and classical south indian dessert recipe made with semolina, ghee and sugar. the recipe is generally made for breakfast and served as an accompaniment to a savory dishes like upma, khara bhath and poha. having said that the recipe can also be served as sweet or dessert for any meal including lunch and dinner",
    description:
      "A simple and classical recipe made with semolina, ghee and sugar.",
  },
  {
    id: "5",
    name: "Wada Pav",
    price: 20,
    type: "Snacks",
    meal: "Breakfast",
    avlaibility: "Yes",
    marathi_name: "वडा-पाव",
    // description: "The dish consists of a deep fried potato dumpling placed inside a bread bun (pav) sliced almost in half through the middle. It is generally accompanied with one or more chutneys and a green chili.",
    description:
      "This is a vegetarian fast food dish native to the state of Maharashtra.",
  },
  {
    id: "6",
    name: "Pattis",
    price: 20,
    type: "Snacks",
    meal: "Breakfast",
    avlaibility: "Yes",
    marathi_name: "पेटीस",
    description:
      "This snack is nothing but potato stuffing between 2 triangle shaped bread slices.",
  },
  {
    id: "7",
    name: "Samosa",
    price: 15,
    type: "Snacks",
    meal: "Breakfast",
    avlaibility: "Yes",
    marathi_name: "समोसा",
    // description:
    //   "A samosa is a fried or baked pastry with a savory filling, including ingredients such as spiced potatoes, onions, peas , herbs and many more.",
    description: "Samosa is a fried or baked pastry with a savory filling of spices potatoes.",
  },
  {
    id: "9",
    name: "Kanda Bhaji",
    price: 15,
    type: "Snacks",
    meal: "Breakfast",
    avlaibility: "Yes",
    marathi_name: "कांदा भजी",
    description:
      "Kanda bhaji are crisp and crunchy fried fritters made mainly with onions and gram flour.",
  },

  {
    id: "10",
    name: "Batata Bhaji",
    price: 25,
    type: "Snacks",
    meal: "Breakfast",
    avlaibility: "Yes",
    marathi_name: "बटाटा भजी",
    description:
      "Batata bhaji are crisp and crunchy fried ovel shaped made mainly with Potato and gram flour.",
  },
  {
    id: "11",
    name: "Single Wada",
    price: 15,
    type: "Snacks",
    meal: "Breakfast",
    avlaibility: "Yes",
    marathi_name: "सिंगल वडा",
    description:
      "The dish consists of a deep fried potato dumpling cooked with Potato, onions, spices and herbs.",
  },
  {
    id: "12",
    name: "Pav Jodi",
    price: 15,
    type: "Snacks",
    meal: "Breakfast",
    avlaibility: "Yes",
    marathi_name: "पाव जोडी ",
    description: "This includes a couple of bread",
  },
  {
    id: "13",
    name: "Idli Sambhar",
    price: 30,
    type: "Snacks",
    meal: "Breakfast",
    avlaibility: "Yes",
    marathi_name: "इडली संभार ",
    // description:
    //   "Idli Sambar is a hearty, satisfying, comforting and a healthy meal of soft fluffy idlis served with savory, spiced and lightly tangy sambar – a vegetable stew made with lentils and assorted vegetables.",
    description: "Idli sambar is a South Indian breakfast meal where idli is served with sambar and chutney.",
  },
  {
    id: "14",
    name: "Single Idli Wada",
    price: 20,
    type: "Snacks",
    meal: "Breakfast",
    avlaibility: "Yes",
    marathi_name: "सिंगल इडली संभार ",
    description: "",
  },
  {
    id: "15",
    name: "Udid Wada Sambhar",
    price: 40,
    type: "Snacks",
    meal: "Breakfast",
    avlaibility: "Yes",
    marathi_name: "उडीद वाडा संभार ",
    description: "",
  },
  {
    id: "16",
    name: "Idli Wada Mix",
    price: 40,
    type: "Snacks",
    meal: "Breakfast",
    avlaibility: "Yes",
    marathi_name: "इडली वडा मिक्स",
    description: "",
  },
  {
    id: "17",
    name: "Batata Wada Sambhar",
    price: 40,
    type: "Snacks",
    meal: "Breakfast",
    avlaibility: "Yes",
    marathi_name: "बटाटा वडा सांभार",
    description: "",
  },
  {
    id: "18",
    name: "Single Wada Sambhar",
    price: 25,
    type: "Snacks",
    meal: "Breakfast",
    avlaibility: "Yes",
    marathi_name: "सिंगल वडा सांभार",
    description: "",
  },
  {
    id: "19",
    name: "Batata Bhaji",
    price: 25,
    type: "Snacks",
    meal: "Breakfast",
    avlaibility: "Yes",
    marathi_name: "बटाटा भजी",
    description: "",
  },
];